INSERT INTO empregado VALUES(1, "funcionario A", "AAA", "12/02/2001", "Rua dos bobos Número 0", 'M', 26.0000, 4, 4);
INSERT INTO empregado VALUES(2, "funcionario A", "AAA", "12/02/2001", "Rua dos bobos Número 0", 'f', 26.0000, 4, 4);
INSERT INTO empregado VALUES(3, "funcionario C", "C", "12/02/2001", "Rua dos bobos Número 0", 'F', 26.0000, 4, 4);
INSERT INTO empregado VALUES(4, "funcionario D", "DDD", "06/10/2021", "Rua dos bobos Número 0", 'M', 32.0000, 5, 5);
INSERT INTO empregado VALUES(5, "funcionario E", "EEE", "10/06/2021", "Rua dos bobos Número 0", 'F', 32.0000, 5, 5);
INSERT INTO empregado VALUES(69, "funcionario F", "FFF", "03/11/2049", "Rua dos bobos Número 0", 'M', 32.0000, 5, 5);
INSERT INTO empregado VALUES(24, "funcionario G", "Silva", "15/07/2024", "Rua dos bobos Número 0", 'F', 17.000, 3, 5);


INSERT INTO departamento VALUES(4, "Informática", 3, "03/11/2022");
INSERT INTO departamento VALUES(5, "Diversão", 2, "28/10/2016");
INSERT INTO departamento VALUES(1, "Música", 24, "04/11/2016");

INSERT INTO projeto VALUES(1, "Lost the Cabaço", "Bloco 19", 4);
INSERT INTO projeto VALUES(2, "Gain the Computer", "Bloco 69", 4);
INSERT INTO projeto VALUES(3, "Drive Forever", "Bloco 66", 5);

INSERT INTO trabalha_para VALUES(1, 1, 70);
INSERT INTO trabalha_para VALUES(2, 2, 80);
INSERT INTO trabalha_para VALUES(4, 3, 100);

INSERT INTO dependente VALUES(1, "dependente 1", "M", "07/09/1822", "Alien");
INSERT INTO dependente VALUES(2, "dependente 2", "F", "08/09/1822", "Batata");
INSERT INTO dependente VALUES(3, "dependente 3", "F", "25/04/1975", "Revolucionário");
INSERT INTO dependente VALUES(4, "dependente 4", "M", "02/06/1984", "Revolucionário");